In [1]:
!pip install -U vnstock

Requirement already satisfied: vnstock in c:\users\admin\anaconda3\lib\site-packages (3.2.6)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (4.12.3)
Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (2.2.2)
Requirement already satisfied: seaborn in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (0.13.2)
Requirement already satisfied: openpyxl in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (3.1.5)
Requirement already satisfied: pydantic in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (2.8.2)
Requirement already satisfied: psutil in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (5.9.0)
Requirement already satisfied: fake_useragent in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (2.2.0)
Requirement already satisfied: vnstock_ezchart in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (0.0.2)
Requirement already satisfied: click in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (8.1.7)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (24.1)
Requirement already satisfied: importlib-metadata>=1.0 in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (7.0.1)
Requirement already satisfied: tenacity in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (8.2.3)
Requirement already satisfied: vnai>=2.0.3 in c:\users\admin\anaconda3\lib\site-packages (from vnstock) (2.1.9)
Requirement already satisfied: zipp>=0.5 in c:\users\admin\anaconda3\lib\site-packages (from importlib-metadata>=1.0->vnstock) (3.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests->vnstock) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->vnstock) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests->vnstock) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->vnstock) (2024.8.30)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\anaconda3\lib\site-packages (from beautifulsoup4->vnstock) (2.5)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from click->vnstock) (0.4.6)
Requirement already satisfied: et-xmlfile in c:\users\admin\anaconda3\lib\site-packages (from openpyxl->vnstock) (1.1.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas->vnstock) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas->vnstock) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas->vnstock) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas->vnstock) (2023.3)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\admin\anaconda3\lib\site-packages (from pydantic->vnstock) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\admin\anaconda3\lib\site-packages (from pydantic->vnstock) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\admin\anaconda3\lib\site-packages (from pydantic->vnstock) (4.11.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\admin\anaconda3\lib\site-packages (from seaborn->vnstock) (3.9.2)
Requirement already satisfied: squarify in c:\users\admin\anaconda3\lib\site-packages (from vnstock_ezchart->vnstock) (0.4.4)
Requirement already satisfied: wordcloud in c:\users\admin\anaconda3\lib\site-packages (from vnstock_ezchart->vnstock) (1.9.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (3.1.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->vnstock) (1.16.0)

In [ ]:
#Tìm tham số tối ưu bằng GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
import numpy as np

In [3]:
import sklearn
import sklearn.metrics as metrics
import inspect

print(sklearn.__version__) 
print(inspect.getfile(metrics.mean_squared_error))  
print(inspect.signature(metrics.mean_squared_error))

1.2.2
C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py
(y_true, y_pred, *, sample_weight=None, multioutput='uniform_average', squared=True)

In [7]:
pip install --upgrade pip

Requirement already satisfied: pip in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (25.1.1)
Collecting pip
  Downloading pip-25.2-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-25.2-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 7.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1
Successfully installed pip-25.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
from vnstock import Listing, Quote, Company, Finance, Trading

In [24]:
listing = Listing()
listing.all_symbols()

     symbol                                         organ_name
0       YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1       YEG                     Công ty Cổ phần Tập đoàn Yeah1
2       YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3       YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4       XPH                    Công ty Cổ phần Xà phòng Hà Nội
...     ...                                                ...
1712    AAS            Công ty Cổ phần Chứng khoán SmartInvest
1713    AAM                    Công ty Cổ Phần Thủy Sản MeKong
1714    AAH                           Công ty Cổ phần Hợp Nhất
1715    AAA                  Công ty Cổ phần Nhựa An Phát Xanh
1716    A32                                 Công ty Cổ phần 32

[1717 rows x 2 columns]

In [30]:
import time
from vnstock import Listing, Vnstock
import os

SAVE_FOLDER = "data_stock"
os.makedirs(SAVE_FOLDER, exist_ok=True)

#Lấy danh sách mã 
listing = Listing(source="VCI")  # chỉ nhận VCI hoặc MSN
symbols_df = listing.all_symbols()
tickers = symbols_df["symbol"].dropna().unique().tolist()

print(f"Tổng số mã: {len(tickers)}")

#Lấy dữ liệu lịch sử cho từng mã
for i, symbol in enumerate(tickers):
    try:
        stock = Vnstock().stock(symbol, "VCI")  # chỉ VCI/MSN
        df = stock.quote.history(start="2024-01-01", end="2025-08-01")
        df.to_csv(f"{SAVE_FOLDER}/{symbol}.csv", index=False)
        print(f"✅ Lưu xong {symbol} ({i+1}/{len(tickers)})")
        time.sleep(1.5)  # nghỉ 1.5 giây để tránh bị chặn
    except Exception as e:
        print(f"❌ Lỗi {symbol}: {e}")
        time.sleep(5)  # nếu lỗi thì nghỉ lâu hơn

Tổng số mã: 1717
✅ Lưu xong YTC (1/1717)
✅ Lưu xong YEG (2/1717)
✅ Lưu xong YBM (3/1717)
✅ Lưu xong YBC (4/1717)
✅ Lưu xong XPH (5/1717)
✅ Lưu xong XMP (6/1717)
✅ Lưu xong XMD (7/1717)
✅ Lưu xong XMC (8/1717)
✅ Lưu xong XLV (9/1717)
✅ Lưu xong XHC (10/1717)
✅ Lưu xong XDH (11/1717)
❌ Lỗi XDC: RetryError[<Future at 0x1d32baa6150 state=finished raised ValueError>]
✅ Lưu xong X77 (13/1717)
✅ Lưu xong X26 (14/1717)
✅ Lưu xong X20 (15/1717)
✅ Lưu xong WTC (16/1717)
✅ Lưu xong WSS (17/1717)
✅ Lưu xong WSB (18/1717)
✅ Lưu xong WCS (19/1717)
✅ Lưu xong VXT (20/1717)
✅ Lưu xong VXP (21/1717)
✅ Lưu xong VXB (22/1717)
✅ Lưu xong VWS (23/1717)
✅ Lưu xong VW3 (24/1717)
✅ Lưu xong VVS (25/1717)
✅ Lưu xong VVN (26/1717)
✅ Lưu xong VUA (27/1717)
✅ Lưu xong VTZ (28/1717)
✅ Lưu xong VTX (29/1717)
✅ Lưu xong VTV (30/1717)
✅ Lưu xong VTS (31/1717)
✅ Lưu xong VTR (32/1717)
✅ Lưu xong VTQ (33/1717)
✅ Lưu xong VTP (34/1717)
✅ Lưu xong VTO (35/1717)
✅ Lưu xong VTM (36/1717)
✅ Lưu xong VTL (37/1717)
✅ Lưu xong VTK (38/1717)
✅ Lưu xong VTJ (39/1717)
✅ Lưu xong VTI (40/1717)
✅ Lưu xong VTH (41/1717)
✅ Lưu xong VTG (42/1717)
✅ Lưu xong VTE (43/1717)
✅ Lưu xong VTD (44/1717)
✅ Lưu xong VTC (45/1717)
✅ Lưu xong VTB (46/1717)
✅ Lưu xong VTA (47/1717)
✅ Lưu xong VST (48/1717)
❌ Lỗi VSP: RetryError[<Future at 0x1d32baf43d0 state=finished raised ValueError>]
✅ Lưu xong VSN (50/1717)
✅ Lưu xong VSM (51/1717)
✅ Lưu xong VSI (52/1717)
✅ Lưu xong VSH (53/1717)
✅ Lưu xong VSG (54/1717)
✅ Lưu xong VSF (55/1717)
✅ Lưu xong VSE (56/1717)
✅ Lưu xong VSC (57/1717)
✅ Lưu xong VSA (58/1717)
✅ Lưu xong VRG (59/1717)
✅ Lưu xong VRE (60/1717)
✅ Lưu xong VRC (61/1717)
✅ Lưu xong VQC (62/1717)
✅ Lưu xong VPW (63/1717)
✅ Lưu xong VPS (64/1717)
✅ Lưu xong VPR (65/1717)
✅ Lưu xong VPL (66/1717)
✅ Lưu xong VPI (67/1717)
✅ Lưu xong VPH (68/1717)
✅ Lưu xong VPG (69/1717)
✅ Lưu xong VPD (70/1717)
✅ Lưu xong VPC (71/1717)
✅ Lưu xong VPB (72/1717)
✅ Lưu xong VPA (73/1717)
✅ Lưu xong VOS (74/1717)
✅ Lưu xong VOC (75/1717)
✅ Lưu xong VNZ (76/1717)
✅ Lưu xong VNY (77/1717)
✅ Lưu xong VNX (78/1717)
✅ Lưu xong VNT (79/1717)
✅ Lưu xong VNS (80/1717)
✅ Lưu xong VNR (81/1717)
✅ Lưu xong VNP (82/1717)
✅ Lưu xong VNM (83/1717)
✅ Lưu xong VNL (84/1717)
✅ Lưu xong VNI (85/1717)
✅ Lưu xong VNH (86/1717)
✅ Lưu xong VNG (87/1717)
✅ Lưu xong VNF (88/1717)
✅ Lưu xong VNE (89/1717)
✅ Lưu xong VND (90/1717)
✅ Lưu xong VNC (91/1717)
✅ Lưu xong VNB (92/1717)
✅ Lưu xong VNA (93/1717)
✅ Lưu xong VMT (94/1717)
✅ Lưu xong VMS (95/1717)
✅ Lưu xong VMK (96/1717)
❌ Lỗi VMI: RetryError[<Future at 0x1d32b827ad0 state=finished raised ValueError>]
✅ Lưu xong VMG (98/1717)
✅ Lưu xong VMD (99/1717)
✅ Lưu xong VMC (100/1717)
✅ Lưu xong VMA (101/1717)
✅ Lưu xong VLW (102/1717)
✅ Lưu xong VLP (103/1717)
✅ Lưu xong VLG (104/1717)
✅ Lưu xong VLF (105/1717)
✅ Lưu xong VLC (106/1717)
✅ Lưu xong VLB (107/1717)
✅ Lưu xong VLA (108/1717)
✅ Lưu xong VKP (109/1717)
❌ Lỗi VKD: RetryError[<Future at 0x1d32b2b1ed0 state=finished raised ValueError>]
✅ Lưu xong VKC (111/1717)
✅ Lưu xong VJC (112/1717)
✅ Lưu xong VIX (113/1717)
✅ Lưu xong VIW (114/1717)
✅ Lưu xong VIT (115/1717)
❌ Lỗi VIS: RetryError[<Future at 0x1d32b9fe650 state=finished raised ValueError>]
✅ Lưu xong VIR (117/1717)
✅ Lưu xong VIP (118/1717)
✅ Lưu xong VIN (119/1717)
✅ Lưu xong VIM (120/1717)
✅ Lưu xong VIH (121/1717)
✅ Lưu xong VIG (122/1717)
✅ Lưu xong VIF (123/1717)
✅ Lưu xong VIE (124/1717)
✅ Lưu xong VID (125/1717)
✅ Lưu xong VIC (126/1717)
✅ Lưu xong VIB (127/1717)
✅ Lưu xong VHM (128/1717)
✅ Lưu xong VHL (129/1717)
❌ Lỗi VHI: RetryError[<Future at 0x1d32b9fdcd0 state=finished raised ValueError>]
✅ Lưu xong VHH (131/1717)
✅ Lưu xong VHG (132/1717)
✅ Lưu xong VHF (133/1717)
✅ Lưu xong VHE (134/1717)
✅ Lưu xong VHD (135/1717)
✅ Lưu xong VHC (136/1717)
✅ Lưu xong VGV (137/1717)
✅ Lưu xong VGT (138/1717)
✅ Lưu xong VGS (139/1717)
✅ Lưu xong VGR (140/1717)
✅ Lưu xong VGP (141/1717)
✅ Lưu xong VGL (142/1717)
✅ Lưu xong VGI (143/1717)
✅ Lưu xong VGG (144/1717)
✅ Lưu xong VGC (145/1717)
✅ Lưu xong VFS (146/1717)
✅ Lưu xong VFR (147/1717)
✅ Lưu xong VFG (148/1717)
✅ Lưu xong VFC (149/1717)
✅ Lưu xong VET (150/1717)
✅ Lưu xong VES (151/1717)
✅ Lưu xong VEF (152/1717)
✅ Lưu xong VEC (153/1717)
✅ Lưu xong VEA (154/1717)
✅ Lưu xong VE9 (155/1717)
✅ Lưu xong VE8 (156/1717)
✅ Lưu xong VE4 (157/1717)
✅ Lưu xong VE3 (158/1717)
✅ Lưu xong VE2 (159/1717)
✅ Lưu xong VE1 (160/1717)
✅ Lưu xong VDT (161/1717)
✅ Lưu xong VDS (162/1717)
✅ Lưu xong VDP (163/1717)
✅ Lưu xong VDN (164/1717)
❌ Lỗi VDM: RetryError[<Future at 0x1d32823c5d0 state=finished raised ValueError>]
✅ Lưu xong VDL (166/1717)
✅ Lưu xong VDG (167/1717)
✅ Lưu xong VDB (168/1717)
✅ Lưu xong VCX (169/1717)
✅ Lưu xong VCW (170/1717)
✅ Lưu xong VCT (171/1717)
✅ Lưu xong VCS (172/1717)
✅ Lưu xong VCR (173/1717)
✅ Lưu xong VCP (174/1717)
✅ Lưu xong VCM (175/1717)
✅ Lưu xong VCI (176/1717)
✅ Lưu xong VCG (177/1717)
✅ Lưu xong VCF (178/1717)
✅ Lưu xong VCE (179/1717)
✅ Lưu xong VCC (180/1717)
✅ Lưu xong VCB (181/1717)
✅ Lưu xong VCA (182/1717)
✅ Lưu xong VC9 (183/1717)
✅ Lưu xong VC7 (184/1717)
✅ Lưu xong VC6 (185/1717)
✅ Lưu xong VC5 (186/1717)
✅ Lưu xong VC3 (187/1717)
✅ Lưu xong VC2 (188/1717)
✅ Lưu xong VC1 (189/1717)
✅ Lưu xong VBH (190/1717)
✅ Lưu xong VBG (191/1717)
✅ Lưu xong VBC (192/1717)
✅ Lưu xong VBB (193/1717)
✅ Lưu xong VAV (194/1717)
❌ Lỗi VAT: RetryError[<Future at 0x1d32b574050 state=finished raised ValueError>]
✅ Lưu xong VAF (196/1717)
✅ Lưu xong VAB (197/1717)
✅ Lưu xong V21 (198/1717)
✅ Lưu xong V15 (199/1717)
✅ Lưu xong V12 (200/1717)
✅ Lưu xong V11 (201/1717)
✅ Lưu xong UXC (202/1717)
✅ Lưu xong USD (203/1717)
✅ Lưu xong USC (204/1717)
✅ Lưu xong UPH (205/1717)
✅ Lưu xong UPC (206/1717)
✅ Lưu xong UNI (207/1717)
✅ Lưu xong UMC (208/1717)
✅ Lưu xong UIC (209/1717)
✅ Lưu xong UEM (210/1717)
✅ Lưu xong UDL (211/1717)
✅ Lưu xong UDJ (212/1717)
✅ Lưu xong UDC (213/1717)
✅ Lưu xong UCT (214/1717)
✅ Lưu xong TYA (215/1717)
✅ Lưu xong TXM (216/1717)
✅ Lưu xong TW3 (217/1717)
❌ Lỗi TVW: RetryError[<Future at 0x1d32bb9f4d0 state=finished raised ValueError>]
✅ Lưu xong TVT (219/1717)
✅ Lưu xong TVS (220/1717)
❌ Lỗi TVP: RetryError[<Future at 0x1d32b7f1c50 state=finished raised ValueError>]
✅ Lưu xong TVN (222/1717)
✅ Lưu xong TVM (223/1717)
✅ Lưu xong TVH (224/1717)
✅ Lưu xong TVG (225/1717)
✅ Lưu xong TVD (226/1717)
✅ Lưu xong TVC (227/1717)
✅ Lưu xong TVB (228/1717)
✅ Lưu xong TVA (229/1717)
✅ Lưu xong TV6 (230/1717)
✅ Lưu xong TV4 (231/1717)
✅ Lưu xong TV3 (232/1717)
✅ Lưu xong TV2 (233/1717)
✅ Lưu xong TV1 (234/1717)
✅ Lưu xong TUG (235/1717)
✅ Lưu xong TTZ (236/1717)
✅ Lưu xong TTT (237/1717)
✅ Lưu xong TTS (238/1717)
✅ Lưu xong TTP (239/1717)
✅ Lưu xong TTN (240/1717)
✅ Lưu xong TTL (241/1717)
✅ Lưu xong TTH (242/1717)
✅ Lưu xong TTG (243/1717)
✅ Lưu xong TTF (244/1717)
✅ Lưu xong TTE (245/1717)
✅ Lưu xong TTD (246/1717)
✅ Lưu xong TTC (247/1717)
✅ Lưu xong TTB (248/1717)
✅ Lưu xong TTA (249/1717)
✅ Lưu xong TT6 (250/1717)
✅ Lưu xong TST (251/1717)
✅ Lưu xong TSJ (252/1717)
✅ Lưu xong TSG (253/1717)
✅ Lưu xong TSD (254/1717)
✅ Lưu xong TSC (255/1717)
✅ Lưu xong TSB (256/1717)
✅ Lưu xong TSA (257/1717)
❌ Lỗi TS5: 'NoneType' object is not subscriptable
✅ Lưu xong TS4 (259/1717)
✅ Lưu xong TS3 (260/1717)
✅ Lưu xong TRV (261/1717)
✅ Lưu xong TRT (262/1717)
✅ Lưu xong TRS (263/1717)
✅ Lưu xong TRC (264/1717)
✅ Lưu xong TRA (265/1717)
✅ Lưu xong TR1 (266/1717)
✅ Lưu xong TQW (267/1717)
✅ Lưu xong TQN (268/1717)
✅ Lưu xong TPS (269/1717)
✅ Lưu xong TPP (270/1717)
✅ Lưu xong TPH (271/1717)
✅ Lưu xong TPC (272/1717)
✅ Lưu xong TPB (273/1717)
✅ Lưu xong TOW (274/1717)
✅ Lưu xong TOT (275/1717)
✅ Lưu xong TOS (276/1717)
✅ Lưu xong TOP (277/1717)
✅ Lưu xong TNW (278/1717)
✅ Lưu xong TNV (279/1717)
✅ Lưu xong TNT (280/1717)
✅ Lưu xong TNS (281/1717)
✅ Lưu xong TNP (282/1717)
✅ Lưu xong TNM (283/1717)
✅ Lưu xong TNI (284/1717)
✅ Lưu xong TNH (285/1717)
✅ Lưu xong TNG (286/1717)
✅ Lưu xong TNC (287/1717)
✅ Lưu xong TNB (288/1717)
✅ Lưu xong TNA (289/1717)
✅ Lưu xong TN1 (290/1717)
✅ Lưu xong TMX (291/1717)
✅ Lưu xong TMW (292/1717)
✅ Lưu xong TMT (293/1717)
✅ Lưu xong TMS (294/1717)
✅ Lưu xong TMP (295/1717)
✅ Lưu xong TMG (296/1717)
✅ Lưu xong TMC (297/1717)
✅ Lưu xong TMB (298/1717)
✅ Lưu xong TLT (299/1717)
✅ Lưu xong TLP (300/1717)
✅ Lưu xong TLI (301/1717)
✅ Lưu xong TLH (302/1717)
✅ Lưu xong TLG (303/1717)
✅ Lưu xong TLD (304/1717)
✅ Lưu xong TL4 (305/1717)
✅ Lưu xong TKU (306/1717)
✅ Lưu xong TKG (307/1717)
✅ Lưu xong TKC (308/1717)
✅ Lưu xong TKA (309/1717)
✅ Lưu xong TJC (310/1717)
✅ Lưu xong TIX (311/1717)
✅ Lưu xong TIS (312/1717)
✅ Lưu xong TIP (313/1717)
✅ Lưu xong TIN (314/1717)
✅ Lưu xong TIG (315/1717)
✅ Lưu xong TIE (316/1717)
✅ Lưu xong TID (317/1717)
✅ Lưu xong THW (318/1717)
✅ Lưu xong THU (319/1717)
✅ Lưu xong THT (320/1717)
✅ Lưu xong THS (321/1717)
✅ Lưu xong THP (322/1717)
✅ Lưu xong THN (323/1717)
✅ Lưu xong THM (324/1717)
❌ Lỗi THI: RetryError[<Future at 0x1d32ba8d650 state=finished raised ValueError>]
✅ Lưu xong THG (326/1717)
✅ Lưu xong THD (327/1717)
✅ Lưu xong THB (328/1717)
✅ Lưu xong TH1 (329/1717)
✅ Lưu xong TGP (330/1717)
✅ Lưu xong TGG (331/1717)
✅ Lưu xong TFC (332/1717)
✅ Lưu xong TET (333/1717)
✅ Lưu xong TEL (334/1717)
✅ Lưu xong TEG (335/1717)
✅ Lưu xong TED (336/1717)
❌ Lỗi TEC: RetryError[<Future at 0x1d32baa5f50 state=finished raised ValueError>]
✅ Lưu xong TDW (338/1717)
✅ Lưu xong TDT (339/1717)
✅ Lưu xong TDS (340/1717)
✅ Lưu xong TDP (341/1717)
✅ Lưu xong TDN (342/1717)
✅ Lưu xong TDM (343/1717)
❌ Lỗi TDI: RetryError[<Future at 0x1d32ba8af50 state=finished raised ValueError>]
✅ Lưu xong TDH (345/1717)
✅ Lưu xong TDG (346/1717)
✅ Lưu xong TDF (347/1717)
✅ Lưu xong TDC (348/1717)
✅ Lưu xong TDB (349/1717)
✅ Lưu xong TD6 (350/1717)
✅ Lưu xong TCW (351/1717)
✅ Lưu xong TCT (352/1717)
✅ Lưu xong TCR (353/1717)
✅ Lưu xong TCO (354/1717)
✅ Lưu xong TCM (355/1717)
✅ Lưu xong TCL (356/1717)
✅ Lưu xong TCK (357/1717)
✅ Lưu xong TCJ (358/1717)
✅ Lưu xong TCI (359/1717)
✅ Lưu xong TCH (360/1717)
✅ Lưu xong TCD (361/1717)
✅ Lưu xong TCB (362/1717)
✅ Lưu xong TC6 (363/1717)
✅ Lưu xong TBX (364/1717)
✅ Lưu xong TBW (365/1717)
✅ Lưu xong TBT (366/1717)
✅ Lưu xong TBR (367/1717)
✅ Lưu xong TBH (368/1717)
✅ Lưu xong TBD (369/1717)
✅ Lưu xong TBC (370/1717)
✅ Lưu xong TB8 (371/1717)
✅ Lưu xong TAW (372/1717)
✅ Lưu xong TAR (373/1717)
❌ Lỗi TAP: RetryError[<Future at 0x1d32bb539d0 state=finished raised ValueError>]
✅ Lưu xong TAN (375/1717)
✅ Lưu xong TAL (376/1717)
❌ Lỗi TAG: RetryError[<Future at 0x1d327576ad0 state=finished raised ValueError>]
❌ Lỗi TAC: 'NoneType' object is not subscriptable
✅ Lưu xong TAB (379/1717)
✅ Lưu xong TA9 (380/1717)
✅ Lưu xong TA6 (381/1717)
✅ Lưu xong TA3 (382/1717)
❌ Lỗi T12: 'NoneType' object is not subscriptable
✅ Lưu xong SZL (384/1717)
✅ Lưu xong SZG (385/1717)
✅ Lưu xong SZE (386/1717)
✅ Lưu xong SZC (387/1717)
✅ Lưu xong SZB (388/1717)
✅ Lưu xong SWC (389/1717)
✅ Lưu xong SVT (390/1717)
✅ Lưu xong SVN (391/1717)
❌ Lỗi SVL: RetryError[<Future at 0x1d32bbea8d0 state=finished raised ValueError>]
✅ Lưu xong SVI (393/1717)
✅ Lưu xong SVH (394/1717)
✅ Lưu xong SVG (395/1717)
✅ Lưu xong SVD (396/1717)
✅ Lưu xong SVC (397/1717)
✅ Lưu xong STW (398/1717)
✅ Lưu xong STT (399/1717)
✅ Lưu xong STS (400/1717)
✅ Lưu xong STP (401/1717)
✅ Lưu xong STL (402/1717)
✅ Lưu xong STK (403/1717)
✅ Lưu xong STH (404/1717)
✅ Lưu xong STG (405/1717)
✅ Lưu xong STC (406/1717)
✅ Lưu xong STB (407/1717)
✅ Lưu xong ST8 (408/1717)
❌ Lỗi SSU: RetryError[<Future at 0x1d32ba8f550 state=finished raised ValueError>]
✅ Lưu xong SSN (410/1717)
✅ Lưu xong SSM (411/1717)
✅ Lưu xong SSI (412/1717)
✅ Lưu xong SSH (413/1717)
✅ Lưu xong SSG (414/1717)
✅ Lưu xong SSF (415/1717)
✅ Lưu xong SSC (416/1717)
✅ Lưu xong SSB (417/1717)
✅ Lưu xong SRT (418/1717)
✅ Lưu xong SRF (419/1717)
✅ Lưu xong SRC (420/1717)
✅ Lưu xong SRB (421/1717)
✅ Lưu xong SRA (422/1717)
✅ Lưu xong SQC (423/1717)
✅ Lưu xong SPV (424/1717)
❌ Lỗi SPP: RetryError[<Future at 0x1d32ba8d3d0 state=finished raised ValueError>]
✅ Lưu xong SPM (426/1717)
✅ Lưu xong SPI (427/1717)
✅ Lưu xong SPH (428/1717)
✅ Lưu xong SPD (429/1717)
✅ Lưu xong SPC (430/1717)
✅ Lưu xong SPB (431/1717)
❌ Lỗi SPA: RetryError[<Future at 0x1d32ac8d150 state=finished raised ValueError>]
✅ Lưu xong SP2 (433/1717)
❌ Lỗi SON: RetryError[<Future at 0x1d32ba315d0 state=finished raised ValueError>]
✅ Lưu xong SNZ (435/1717)
✅ Lưu xong SNC (436/1717)
✅ Lưu xong SMT (437/1717)
✅ Lưu xong SMN (438/1717)
✅ Lưu xong SMC (439/1717)
✅ Lưu xong SMB (440/1717)
✅ Lưu xong SMA (441/1717)
✅ Lưu xong SLS (442/1717)
✅ Lưu xong SKV (443/1717)
✅ Lưu xong SKN (444/1717)
✅ Lưu xong SKH (445/1717)
✅ Lưu xong SKG (446/1717)
✅ Lưu xong SJS (447/1717)
✅ Lưu xong SJM (448/1717)
✅ Lưu xong SJG (449/1717)
✅ Lưu xong SJF (450/1717)
✅ Lưu xong SJE (451/1717)
✅ Lưu xong SJD (452/1717)
✅ Lưu xong SJC (453/1717)
✅ Lưu xong SJ1 (454/1717)
✅ Lưu xong SIV (455/1717)
✅ Lưu xong SIP (456/1717)
✅ Lưu xong SII (457/1717)
✅ Lưu xong SIG (458/1717)
✅ Lưu xong SID (459/1717)
❌ Lỗi SIC: RetryError[<Future at 0x1d32ba8a350 state=finished raised ValueError>]
❌ Lỗi SHX: RetryError[<Future at 0x1d32b5ce5d0 state=finished raised ValueError>]
✅ Lưu xong SHS (462/1717)
✅ Lưu xong SHP (463/1717)
✅ Lưu xong SHN (464/1717)
✅ Lưu xong SHI (465/1717)
✅ Lưu xong SHG (466/1717)
✅ Lưu xong SHE (467/1717)
✅ Lưu xong SHC (468/1717)
✅ Lưu xong SHB (469/1717)
✅ Lưu xong SHA (470/1717)
✅ Lưu xong SGT (471/1717)
✅ Lưu xong SGS (472/1717)
✅ Lưu xong SGR (473/1717)
✅ Lưu xong SGP (474/1717)
❌ Lỗi SGO: RetryError[<Future at 0x1d32ba63cd0 state=finished raised ValueError>]
✅ Lưu xong SGN (476/1717)
✅ Lưu xong SGI (477/1717)
✅ Lưu xong SGH (478/1717)
✅ Lưu xong SGD (479/1717)
✅ Lưu xong SGC (480/1717)
✅ Lưu xong SGB (481/1717)
✅ Lưu xong SFN (482/1717)
✅ Lưu xong SFI (483/1717)
✅ Lưu xong SFG (484/1717)
✅ Lưu xong SFC (485/1717)
✅ Lưu xong SEP (486/1717)
✅ Lưu xong SED (487/1717)
✅ Lưu xong SEB (488/1717)
✅ Lưu xong SEA (489/1717)
✅ Lưu xong SDY (490/1717)
✅ Lưu xong SDX (491/1717)
✅ Lưu xong SDV (492/1717)
✅ Lưu xong SDU (493/1717)
✅ Lưu xong SDT (494/1717)
✅ Lưu xong SDP (495/1717)
✅ Lưu xong SDN (496/1717)
✅ Lưu xong SDK (497/1717)
✅ Lưu xong SDJ (498/1717)
❌ Lỗi SDH: RetryError[<Future at 0x1d32bc052d0 state=finished raised ValueError>]
✅ Lưu xong SDG (500/1717)
✅ Lưu xong SDD (501/1717)
✅ Lưu xong SDC (502/1717)
✅ Lưu xong SDB (503/1717)
✅ Lưu xong SDA (504/1717)
✅ Lưu xong SD9 (505/1717)
✅ Lưu xong SD8 (506/1717)
✅ Lưu xong SD7 (507/1717)
✅ Lưu xong SD6 (508/1717)
✅ Lưu xong SD5 (509/1717)
✅ Lưu xong SD4 (510/1717)
✅ Lưu xong SD3 (511/1717)
✅ Lưu xong SD2 (512/1717)
✅ Lưu xong SD1 (513/1717)
✅ Lưu xong SCY (514/1717)
❌ Lỗi SCV: RetryError[<Future at 0x1d32bc068d0 state=finished raised ValueError>]
✅ Lưu xong SCS (516/1717)
✅ Lưu xong SCR (517/1717)
✅ Lưu xong SCO (518/1717)
✅ Lưu xong SCL (519/1717)
✅ Lưu xong SCJ (520/1717)
✅ Lưu xong SCI (521/1717)
✅ Lưu xong SCG (522/1717)
✅ Lưu xong SCD (523/1717)
✅ Lưu xong SCC (524/1717)
❌ Lỗi SCA: RetryError[<Future at 0x1d32ba325d0 state=finished raised ValueError>]
✅ Lưu xong SC5 (526/1717)
✅ Lưu xong SBV (527/1717)
✅ Lưu xong SBT (528/1717)
✅ Lưu xong SBS (529/1717)
✅ Lưu xong SBR (530/1717)
✅ Lưu xong SBM (531/1717)
✅ Lưu xong SBL (532/1717)
✅ Lưu xong SBH (533/1717)
✅ Lưu xong SBG (534/1717)
✅ Lưu xong SBD (535/1717)
✅ Lưu xong SBB (536/1717)
✅ Lưu xong SBA (537/1717)
✅ Lưu xong SB1 (538/1717)
✅ Lưu xong SAV (539/1717)
✅ Lưu xong SAS (540/1717)
✅ Lưu xong SAP (541/1717)
✅ Lưu xong SAM (542/1717)
✅ Lưu xong SAL (543/1717)
✅ Lưu xong SAF (544/1717)
✅ Lưu xong SAC (545/1717)
✅ Lưu xong SAB (546/1717)
✅ Lưu xong S99 (547/1717)
✅ Lưu xong S96 (548/1717)
✅ Lưu xong S74 (549/1717)
✅ Lưu xong S72 (550/1717)
✅ Lưu xong S55 (551/1717)
✅ Lưu xong S4A (552/1717)
✅ Lưu xong S27 (553/1717)
✅ Lưu xong S12 (554/1717)
✅ Lưu xong RYG (555/1717)
✅ Lưu xong RTB (556/1717)
❌ Lỗi ROS: RetryError[<Future at 0x1d32823fb50 state=finished raised ValueError>]
✅ Lưu xong RIC (558/1717)
✅ Lưu xong RGC (559/1717)
✅ Lưu xong REE (560/1717)
✅ Lưu xong RDP (561/1717)
✅ Lưu xong RCL (562/1717)
✅ Lưu xong RCD (563/1717)
✅ Lưu xong RCC (564/1717)
✅ Lưu xong RBC (565/1717)
✅ Lưu xong RAT (566/1717)
✅ Lưu xong RAL (567/1717)
✅ Lưu xong QTP (568/1717)
✅ Lưu xong QTC (569/1717)
✅ Lưu xong QST (570/1717)
✅ Lưu xong QSP (571/1717)
✅ Lưu xong QPH (572/1717)
✅ Lưu xong QNW (573/1717)
✅ Lưu xong QNU (574/1717)
✅ Lưu xong QNT (575/1717)
✅ Lưu xong QNS (576/1717)
✅ Lưu xong QNP (577/1717)
✅ Lưu xong QNC (578/1717)
❌ Lỗi QLT: RetryError[<Future at 0x1d32823c5d0 state=finished raised ValueError>]
❌ Lỗi QLD: RetryError[<Future at 0x1d32b869fd0 state=finished raised ValueError>]
✅ Lưu xong QHW (581/1717)
✅ Lưu xong QHD (582/1717)
✅ Lưu xong QCG (583/1717)
✅ Lưu xong QCC (584/1717)
✅ Lưu xong QBS (585/1717)
❌ Lỗi PYU: 'NoneType' object is not subscriptable
✅ Lưu xong PXT (587/1717)
✅ Lưu xong PXS (588/1717)
✅ Lưu xong PXM (589/1717)
✅ Lưu xong PXL (590/1717)
✅ Lưu xong PXI (591/1717)
✅ Lưu xong PXC (592/1717)
✅ Lưu xong PXA (593/1717)
✅ Lưu xong PX1 (594/1717)
✅ Lưu xong PWS (595/1717)
✅ Lưu xong PWA (596/1717)
✅ Lưu xong PVY (597/1717)
✅ Lưu xong PVX (598/1717)
✅ Lưu xong PVV (599/1717)
✅ Lưu xong PVT (600/1717)
✅ Lưu xong PVS (601/1717)
✅ Lưu xong PVR (602/1717)
✅ Lưu xong PVP (603/1717)
✅ Lưu xong PVO (604/1717)
✅ Lưu xong PVM (605/1717)
✅ Lưu xong PVL (606/1717)
✅ Lưu xong PVI (607/1717)
✅ Lưu xong PVH (608/1717)
✅ Lưu xong PVG (609/1717)
✅ Lưu xong PVE (610/1717)
✅ Lưu xong PVD (611/1717)
✅ Lưu xong PVC (612/1717)
✅ Lưu xong PVB (613/1717)
✅ Lưu xong PVA (614/1717)
✅ Lưu xong PV2 (615/1717)
✅ Lưu xong PTX (616/1717)
✅ Lưu xong PTV (617/1717)
✅ Lưu xong PTT (618/1717)
✅ Lưu xong PTS (619/1717)
✅ Lưu xong PTP (620/1717)
✅ Lưu xong PTO (621/1717)
❌ Lỗi PTN: RetryError[<Future at 0x1d32bb521d0 state=finished raised ValueError>]
✅ Lưu xong PTL (623/1717)
✅ Lưu xong PTI (624/1717)
✅ Lưu xong PTH (625/1717)
✅ Lưu xong PTG (626/1717)
✅ Lưu xong PTE (627/1717)
✅ Lưu xong PTD (628/1717)
✅ Lưu xong PTC (629/1717)
✅ Lưu xong PTB (630/1717)
✅ Lưu xong PSW (631/1717)
✅ Lưu xong PSP (632/1717)
✅ Lưu xong PSN (633/1717)
✅ Lưu xong PSL (634/1717)
✅ Lưu xong PSI (635/1717)
✅ Lưu xong PSH (636/1717)
✅ Lưu xong PSG (637/1717)
✅ Lưu xong PSE (638/1717)
✅ Lưu xong PSD (639/1717)
✅ Lưu xong PSC (640/1717)
✅ Lưu xong PSB (641/1717)
✅ Lưu xong PRT (642/1717)
✅ Lưu xong PRO (643/1717)
✅ Lưu xong PRE (644/1717)
✅ Lưu xong PRC (645/1717)
✅ Lưu xong PQN (646/1717)
✅ Lưu xong PPY (647/1717)
✅ Lưu xong PPT (648/1717)
✅ Lưu xong PPS (649/1717)
✅ Lưu xong PPP (650/1717)
✅ Lưu xong PPI (651/1717)
✅ Lưu xong PPH (652/1717)
✅ Lưu xong PPE (653/1717)
✅ Lưu xong PPC (654/1717)
✅ Lưu xong POW (655/1717)
✅ Lưu xong POV (656/1717)
✅ Lưu xong POT (657/1717)
✅ Lưu xong POS (658/1717)
✅ Lưu xong POM (659/1717)
✅ Lưu xong POB (660/1717)
✅ Lưu xong PNT (661/1717)
✅ Lưu xong PNP (662/1717)
✅ Lưu xong PNJ (663/1717)
✅ Lưu xong PNG (664/1717)
✅ Lưu xong PND (665/1717)
✅ Lưu xong PNC (666/1717)
✅ Lưu xong PMW (667/1717)
✅ Lưu xong PMT (668/1717)
✅ Lưu xong PMS (669/1717)
✅ Lưu xong PMP (670/1717)
✅ Lưu xong PMJ (671/1717)
✅ Lưu xong PMG (672/1717)
✅ Lưu xong PMC (673/1717)
✅ Lưu xong PMB (674/1717)
✅ Lưu xong PLX (675/1717)
✅ Lưu xong PLP (676/1717)
✅ Lưu xong PLO (677/1717)
✅ Lưu xong PLE (678/1717)
✅ Lưu xong PLC (679/1717)
✅ Lưu xong PLA (680/1717)
✅ Lưu xong PJT (681/1717)
✅ Lưu xong PJS (682/1717)
✅ Lưu xong PJC (683/1717)
✅ Lưu xong PIV (684/1717)
✅ Lưu xong PIT (685/1717)
✅ Lưu xong PIS (686/1717)
✅ Lưu xong PID (687/1717)
✅ Lưu xong PIC (688/1717)
✅ Lưu xong PIA (689/1717)
✅ Lưu xong PHS (690/1717)
✅ Lưu xong PHR (691/1717)
✅ Lưu xong PHP (692/1717)
✅ Lưu xong PHN (693/1717)
✅ Lưu xong PHH (694/1717)
✅ Lưu xong PHC (695/1717)
✅ Lưu xong PGV (696/1717)
✅ Lưu xong PGT (697/1717)
✅ Lưu xong PGS (698/1717)
✅ Lưu xong PGN (699/1717)
✅ Lưu xong PGI (700/1717)
✅ Lưu xong PGD (701/1717)
✅ Lưu xong PGC (702/1717)
✅ Lưu xong PGB (703/1717)
✅ Lưu xong PFL (704/1717)

In [3]:
import os
import pandas as pd

folder_path = r"E:\New folder\stock\data_stock"

# Lấy danh sách các file CSV
csv_files = [f for f in os.listdir(folder_path) if f.endswith(".csv")]

dataframes = []

for i, file in enumerate(csv_files):
    file_path = os.path.join(folder_path, file)
    try:
        df = pd.read_csv(file_path)
        df["symbol"] = file.replace(".csv", "")  # thêm cột mã chứng khoán
        dataframes.append(df)
        print(f"Đã đọc {file} ({i+1}/{len(csv_files)})")
    except Exception as e:
        print(f"Lỗi khi đọc {file}: {e}")

# Gộp tất cả DataFrame lại
merged_df = pd.concat(dataframes, ignore_index=True,encoding="utf-8-sig")

# Lưu thành csv
output_path = r"E:\New folder\stock\all_stocks.csv"
merged_df.to_csv(output_path, index=False)

print(f" Đã gộp {len(csv_files)} file CSV thành {output_path}")
print(f"Tổng số dòng: {len(merged_df)}")

Đã đọc A32.csv (1/1620)
Đã đọc AAA.csv (2/1620)
Đã đọc AAH.csv (3/1620)
Đã đọc AAM.csv (4/1620)
Đã đọc AAS.csv (5/1620)
Đã đọc AAT.csv (6/1620)
Đã đọc AAV.csv (7/1620)
Đã đọc ABB.csv (8/1620)
Đã đọc ABC.csv (9/1620)
Đã đọc ABI.csv (10/1620)
Đã đọc ABR.csv (11/1620)
Đã đọc ABS.csv (12/1620)
Đã đọc ABT.csv (13/1620)
Đã đọc ABW.csv (14/1620)
Đã đọc ACB.csv (15/1620)
Đã đọc ACC.csv (16/1620)
Đã đọc ACE.csv (17/1620)
Đã đọc ACG.csv (18/1620)
Đã đọc ACL.csv (19/1620)
Đã đọc ACM.csv (20/1620)
Đã đọc ACS.csv (21/1620)
Đã đọc ACV.csv (22/1620)
Đã đọc ADC.csv (23/1620)
Đã đọc ADG.csv (24/1620)
Đã đọc ADP.csv (25/1620)
Đã đọc ADS.csv (26/1620)
Đã đọc AFX.csv (27/1620)
Đã đọc AG1.csv (28/1620)
Đã đọc AGF.csv (29/1620)
Đã đọc AGG.csv (30/1620)
Đã đọc AGM.csv (31/1620)
Đã đọc AGP.csv (32/1620)
Đã đọc AGR.csv (33/1620)
Đã đọc AGX.csv (34/1620)
Đã đọc AIC.csv (35/1620)
Đã đọc AIG.csv (36/1620)
Đã đọc ALT.csv (37/1620)
Đã đọc ALV.csv (38/1620)
Đã đọc AMC.csv (39/1620)
Đã đọc AMD.csv (40/1620)
Đã đọc AME.csv (41/1620)
Đã đọc AMP.csv (42/1620)
Đã đọc AMS.csv (43/1620)
Đã đọc AMV.csv (44/1620)
Đã đọc ANT.csv (45/1620)
Đã đọc ANV.csv (46/1620)
Đã đọc APC.csv (47/1620)
Đã đọc APF.csv (48/1620)
Đã đọc APG.csv (49/1620)
Đã đọc APH.csv (50/1620)
Đã đọc API.csv (51/1620)
Đã đọc APL.csv (52/1620)
Đã đọc APP.csv (53/1620)
Đã đọc APS.csv (54/1620)
Đã đọc APT.csv (55/1620)
Đã đọc ARM.csv (56/1620)
Đã đọc ART.csv (57/1620)
Đã đọc ASA.csv (58/1620)
Đã đọc ASG.csv (59/1620)
Đã đọc ASM.csv (60/1620)
Đã đọc ASP.csv (61/1620)
Đã đọc AST.csv (62/1620)
Đã đọc ATA.csv (63/1620)
Đã đọc ATB.csv (64/1620)
Đã đọc ATG.csv (65/1620)
Đã đọc ATS.csv (66/1620)
Đã đọc AVC.csv (67/1620)
Đã đọc AVF.csv (68/1620)
Đã đọc AVG.csv (69/1620)
Đã đọc B82.csv (70/1620)
Đã đọc BAB.csv (71/1620)
Đã đọc BAF.csv (72/1620)
Đã đọc BAL.csv (73/1620)
Đã đọc BAX.csv (74/1620)
Đã đọc BBC.csv (75/1620)
Đã đọc BBH.csv (76/1620)
Đã đọc BBM.csv (77/1620)
Đã đọc BBS.csv (78/1620)
Đã đọc BBT.csv (79/1620)
Đã đọc BCA.csv (80/1620)
Đã đọc BCB.csv (81/1620)
Đã đọc BCC.csv (82/1620)
Đã đọc BCE.csv (83/1620)
Đã đọc BCF.csv (84/1620)
Đã đọc BCG.csv (85/1620)
Đã đọc BCM.csv (86/1620)
Đã đọc BCO.csv (87/1620)
Đã đọc BCP.csv (88/1620)
Đã đọc BCR.csv (89/1620)
Đã đọc BCV.csv (90/1620)
Đã đọc BDB.csv (91/1620)
Đã đọc BDG.csv (92/1620)
Đã đọc BDT.csv (93/1620)
Đã đọc BDW.csv (94/1620)
Đã đọc BED.csv (95/1620)
Đã đọc BEL.csv (96/1620)
Đã đọc BFC.csv (97/1620)
Đã đọc BGE.csv (98/1620)
Đã đọc BGW.csv (99/1620)
Đã đọc BHA.csv (100/1620)
Đã đọc BHC.csv (101/1620)
Đã đọc BHG.csv (102/1620)
Đã đọc BHH.csv (103/1620)
Đã đọc BHI.csv (104/1620)
Đã đọc BHK.csv (105/1620)
Đã đọc BHN.csv (106/1620)
Đã đọc BHP.csv (107/1620)
Đã đọc BIC.csv (108/1620)
Đã đọc BID.csv (109/1620)
Đã đọc BIG.csv (110/1620)
Đã đọc BII.csv (111/1620)
Đã đọc BIO.csv (112/1620)
Đã đọc BKC.csv (113/1620)
Đã đọc BKG.csv (114/1620)
Đã đọc BLF.csv (115/1620)
Đã đọc BLI.csv (116/1620)
Đã đọc BLN.csv (117/1620)
Đã đọc BLT.csv (118/1620)
Đã đọc BLW.csv (119/1620)
Đã đọc BMC.csv (120/1620)
Đã đọc BMD.csv (121/1620)
Đã đọc BMF.csv (122/1620)
Đã đọc BMG.csv (123/1620)
Đã đọc BMI.csv (124/1620)
Đã đọc BMJ.csv (125/1620)
Đã đọc BMK.csv (126/1620)
Đã đọc BMN.csv (127/1620)
Đã đọc BMP.csv (128/1620)
Đã đọc BMS.csv (129/1620)
Đã đọc BMV.csv (130/1620)
Đã đọc BNA.csv (131/1620)
Đã đọc BNW.csv (132/1620)
Đã đọc BOT.csv (133/1620)
Đã đọc BPC.csv (134/1620)
Đã đọc BQB.csv (135/1620)
Đã đọc BRC.csv (136/1620)
Đã đọc BRR.csv (137/1620)
Đã đọc BRS.csv (138/1620)
Đã đọc BSA.csv (139/1620)
Đã đọc BSC.csv (140/1620)
Đã đọc BSD.csv (141/1620)
Đã đọc BSG.csv (142/1620)
Đã đọc BSH.csv (143/1620)
Đã đọc BSI.csv (144/1620)
Đã đọc BSL.csv (145/1620)
Đã đọc BSP.csv (146/1620)
Đã đọc BSQ.csv (147/1620)
Đã đọc BSR.csv (148/1620)
Đã đọc BST.csv (149/1620)
Đã đọc BT1.csv (150/1620)
Đã đọc BT6.csv (151/1620)
Đã đọc BTB.csv (152/1620)
Đã đọc BTD.csv (153/1620)
Đã đọc BTG.csv (154/1620)
Đã đọc BTH.csv (155/1620)
Đã đọc BTN.csv (156/1620)
Đã đọc BTP.csv (157/1620)
Đã đọc BTS.csv (158/1620)
Đã đọc BTT.csv (159/1620)
Đã đọc BTU.csv (160/1620)
Đã đọc BTV.csv (161/1620)
Đã đọc BTW.csv (162/1620)
Đã đọc BVB.csv (163/1620)
Đã đọc BVG.csv (164/1620)
Đã đọc BVH.csv (165/1620)
Đã đọc BVL.csv (166/1620)
Đã đọc BVN.csv (167/1620)
Đã đọc BVS.csv (168/1620)
Đã đọc BWA.csv (169/1620)
Đã đọc BWE.csv (170/1620)
Đã đọc BWS.csv (171/1620)
Đã đọc BXH.csv (172/1620)
Đã đọc C12.csv (173/1620)
Đã đọc C21.csv (174/1620)
Đã đọc C22.csv (175/1620)
Đã đọc C32.csv (176/1620)
Đã đọc C47.csv (177/1620)
Đã đọc C4G.csv (178/1620)
Đã đọc C69.csv (179/1620)
Đã đọc C92.csv (180/1620)
Đã đọc CAB.csv (181/1620)
Đã đọc CAD.csv (182/1620)
Đã đọc CAG.csv (183/1620)
Đã đọc CAN.csv (184/1620)
Đã đọc CAP.csv (185/1620)
Đã đọc CAR.csv (186/1620)
Đã đọc CAT.csv (187/1620)
Đã đọc CAV.csv (188/1620)
Đã đọc CBI.csv (189/1620)
Đã đọc CBS.csv (190/1620)
Đã đọc CC1.csv (191/1620)
Đã đọc CC4.csv (192/1620)
Đã đọc CCA.csv (193/1620)
Đã đọc CCC.csv (194/1620)
Đã đọc CCI.csv (195/1620)
Đã đọc CCL.csv (196/1620)
Đã đọc CCM.csv (197/1620)
Đã đọc CCP.csv (198/1620)
Đã đọc CCR.csv (199/1620)
Đã đọc CCT.csv (200/1620)
Đã đọc CCV.csv (201/1620)
Đã đọc CDC.csv (202/1620)
Đã đọc CDG.csv (203/1620)
Đã đọc CDH.csv (204/1620)
Đã đọc CDN.csv (205/1620)
Đã đọc CDO.csv (206/1620)
Đã đọc CDP.csv (207/1620)
Đã đọc CDR.csv (208/1620)
Đã đọc CE1.csv (209/1620)
Đã đọc CEG.csv (210/1620)
Đã đọc CEN.csv (211/1620)
Đã đọc CEO.csv (212/1620)
Đã đọc CET.csv (213/1620)
Đã đọc CFM.csv (214/1620)
Đã đọc CFV.csv (215/1620)
Đã đọc CGV.csv (216/1620)
Đã đọc CH5.csv (217/1620)
Đã đọc CHC.csv (218/1620)
Đã đọc CHP.csv (219/1620)
Đã đọc CHS.csv (220/1620)
Đã đọc CI5.csv (221/1620)
Đã đọc CIA.csv (222/1620)
Đã đọc CID.csv (223/1620)
Đã đọc CIG.csv (224/1620)
Đã đọc CII.csv (225/1620)
Đã đọc CIP.csv (226/1620)
Đã đọc CJC.csv (227/1620)
Đã đọc CK8.csv (228/1620)
Đã đọc CKA.csv (229/1620)
Đã đọc CKD.csv (230/1620)
Đã đọc CKG.csv (231/1620)
Đã đọc CKV.csv (232/1620)
Đã đọc CLC.csv (233/1620)
Đã đọc CLG.csv (234/1620)
Đã đọc CLH.csv (235/1620)
Đã đọc CLL.csv (236/1620)
Đã đọc CLM.csv (237/1620)
Đã đọc CLW.csv (238/1620)
Đã đọc CLX.csv (239/1620)
Đã đọc CMC.csv (240/1620)
Đã đọc CMD.csv (241/1620)
Đã đọc CMF.csv (242/1620)
Đã đọc CMG.csv (243/1620)
Đã đọc CMI.csv (244/1620)
Đã đọc CMK.csv (245/1620)
Đã đọc CMM.csv (246/1620)
Đã đọc CMN.csv (247/1620)
Đã đọc CMP.csv (248/1620)
Đã đọc CMS.csv (249/1620)
Đã đọc CMT.csv (250/1620)
Đã đọc CMV.csv (251/1620)
Đã đọc CMW.csv (252/1620)
Đã đọc CMX.csv (253/1620)
Đã đọc CNA.csv (254/1620)
Đã đọc CNC.csv (255/1620)
Đã đọc CNG.csv (256/1620)
Đã đọc CNN.csv (257/1620)
Đã đọc CNT.csv (258/1620)
Đã đọc COM.csv (259/1620)
Đã đọc CPA.csv (260/1620)
Đã đọc CPC.csv (261/1620)
Đã đọc CPH.csv (262/1620)
Đã đọc CPI.csv (263/1620)
Đã đọc CQN.csv (264/1620)
Đã đọc CQT.csv (265/1620)
Đã đọc CRC.csv (266/1620)
Đã đọc CRE.csv (267/1620)
Đã đọc CSC.csv (268/1620)
Đã đọc CSI.csv (269/1620)
Đã đọc CSM.csv (270/1620)
Đã đọc CST.csv (271/1620)
Đã đọc CSV.csv (272/1620)
Đã đọc CT3.csv (273/1620)
Đã đọc CT6.csv (274/1620)
Đã đọc CTA.csv (275/1620)
Đã đọc CTB.csv (276/1620)
Đã đọc CTC.csv (277/1620)
Đã đọc CTD.csv (278/1620)
Đã đọc CTF.csv (279/1620)
Đã đọc CTG.csv (280/1620)
Đã đọc CTI.csv (281/1620)
Đã đọc CTN.csv (282/1620)
Đã đọc CTP.csv (283/1620)
Đã đọc CTR.csv (284/1620)
Đã đọc CTS.csv (285/1620)
Đã đọc CTT.csv (286/1620)
Đã đọc CTW.csv (287/1620)
Đã đọc CTX.csv (288/1620)
Đã đọc CVN.csv (289/1620)
Đã đọc CVT.csv (290/1620)
Đã đọc CX8.csv (291/1620)
Đã đọc CYC.csv (292/1620)
Đã đọc D11.csv (293/1620)
Đã đọc D17.csv (294/1620)
Đã đọc D2D.csv (295/1620)
Đã đọc DAC.csv (296/1620)
Đã đọc DAD.csv (297/1620)
Đã đọc DAE.csv (298/1620)
Đã đọc DAG.csv (299/1620)
Đã đọc DAH.csv (300/1620)
Đã đọc DAN.csv (301/1620)
Đã đọc DAS.csv (302/1620)
Đã đọc DAT.csv (303/1620)
Đã đọc DBC.csv (304/1620)
Đã đọc DBD.csv (305/1620)
Đã đọc DBM.csv (306/1620)
Đã đọc DBT.csv (307/1620)
Đã đọc DC1.csv (308/1620)
Đã đọc DC2.csv (309/1620)
Đã đọc DC4.csv (310/1620)
Đã đọc DCF.csv (311/1620)
Đã đọc DCG.csv (312/1620)
Đã đọc DCH.csv (313/1620)
Đã đọc DCL.csv (314/1620)
Đã đọc DCM.csv (315/1620)
Đã đọc DCR.csv (316/1620)
Đã đọc DCS.csv (317/1620)
Đã đọc DCT.csv (318/1620)
Đã đọc DDB.csv (319/1620)
Đã đọc DDG.csv (320/1620)
Đã đọc DDH.csv (321/1620)
Đã đọc DDM.csv (322/1620)
Đã đọc DDN.csv (323/1620)
Đã đọc DDV.csv (324/1620)
Đã đọc DFC.csv (325/1620)
Đã đọc DFF.csv (326/1620)
Đã đọc DGC.csv (327/1620)
Đã đọc DGT.csv (328/1620)
Đã đọc DGW.csv (329/1620)
Đã đọc DHA.csv (330/1620)
Đã đọc DHB.csv (331/1620)
Đã đọc DHC.csv (332/1620)
Đã đọc DHD.csv (333/1620)
Đã đọc DHG.csv (334/1620)
Đã đọc DHM.csv (335/1620)
Đã đọc DHN.csv (336/1620)
Đã đọc DHP.csv (337/1620)
Đã đọc DHT.csv (338/1620)
Đã đọc DIC.csv (339/1620)
Đã đọc DID.csv (340/1620)
Đã đọc DIG.csv (341/1620)
Đã đọc DIH.csv (342/1620)
Đã đọc DKC.csv (343/1620)
Đã đọc DKG.csv (344/1620)
Đã đọc DKW.csv (345/1620)
Đã đọc DL1.csv (346/1620)
Đã đọc DLD.csv (347/1620)
Đã đọc DLG.csv (348/1620)
Đã đọc DLR.csv (349/1620)
Đã đọc DLT.csv (350/1620)
Đã đọc DM7.csv (351/1620)
Đã đọc DMC.csv (352/1620)
Đã đọc DMN.csv (353/1620)
Đã đọc DMS.csv (354/1620)
Đã đọc DNA.csv (355/1620)
Đã đọc DNC.csv (356/1620)
Đã đọc DND.csv (357/1620)
Đã đọc DNE.csv (358/1620)
Đã đọc DNH.csv (359/1620)
Đã đọc DNL.csv (360/1620)
Đã đọc DNM.csv (361/1620)
Đã đọc DNN.csv (362/1620)
Đã đọc DNP.csv (363/1620)
Đã đọc DNT.csv (364/1620)
Đã đọc DNW.csv (365/1620)
Đã đọc DOC.csv (366/1620)
Đã đọc DOP.csv (367/1620)
Đã đọc DP1.csv (368/1620)
Đã đọc DP2.csv (369/1620)
Đã đọc DP3.csv (370/1620)
Đã đọc DPC.csv (371/1620)
Đã đọc DPG.csv (372/1620)
Đã đọc DPH.csv (373/1620)
Đã đọc DPM.csv (374/1620)
Đã đọc DPP.csv (375/1620)
Đã đọc DPR.csv (376/1620)
Đã đọc DPS.csv (377/1620)
Đã đọc DQC.csv (378/1620)
Đã đọc DRC.csv (379/1620)
Đã đọc DRG.csv (380/1620)
Đã đọc DRH.csv (381/1620)
Đã đọc DRI.csv (382/1620)
Đã đọc DRL.csv (383/1620)
Đã đọc DS3.csv (384/1620)
Đã đọc DSC.csv (385/1620)
Đã đọc DSD.csv (386/1620)
Đã đọc DSE.csv (387/1620)
Đã đọc DSG.csv (388/1620)
Đã đọc DSH.csv (389/1620)
Đã đọc DSN.csv (390/1620)
Đã đọc DSP.csv (391/1620)
Đã đọc DST.csv (392/1620)
Đã đọc DSV.csv (393/1620)
Đã đọc DTA.csv (394/1620)
Đã đọc DTB.csv (395/1620)
Đã đọc DTC.csv (396/1620)
Đã đọc DTD.csv (397/1620)
Đã đọc DTE.csv (398/1620)
Đã đọc DTG.csv (399/1620)
Đã đọc DTH.csv (400/1620)
Đã đọc DTI.csv (401/1620)
Đã đọc DTK.csv (402/1620)
Đã đọc DTL.csv (403/1620)
Đã đọc DTP.csv (404/1620)
Đã đọc DTT.csv (405/1620)
Đã đọc DTV.csv (406/1620)
Đã đọc DUS.csv (407/1620)
Đã đọc DVC.csv (408/1620)
Đã đọc DVG.csv (409/1620)
Đã đọc DVM.csv (410/1620)
Đã đọc DVN.csv (411/1620)
Đã đọc DVP.csv (412/1620)
Đã đọc DVT.csv (413/1620)
Đã đọc DVW.csv (414/1620)
Đã đọc DWC.csv (415/1620)
Đã đọc DWS.csv (416/1620)
Đã đọc DXG.csv (417/1620)
Đã đọc DXL.csv (418/1620)
Đã đọc DXP.csv (419/1620)
Đã đọc DXS.csv (420/1620)
Đã đọc DXV.csv (421/1620)
Đã đọc DZM.csv (422/1620)
Đã đọc E12.csv (423/1620)
Đã đọc E29.csv (424/1620)
Đã đọc EBS.csv (425/1620)
Đã đọc ECI.csv (426/1620)
Đã đọc ECO.csv (427/1620)
Đã đọc EFI.csv (428/1620)
Đã đọc EIB.csv (429/1620)
Đã đọc EIC.csv (430/1620)
Đã đọc EID.csv (431/1620)
Đã đọc EIN.csv (432/1620)
Đã đọc ELC.csv (433/1620)
Đã đọc EME.csv (434/1620)
Đã đọc EMG.csv (435/1620)
Đã đọc EMS.csv (436/1620)
Đã đọc EPC.csv (437/1620)
Đã đọc EPH.csv (438/1620)
Đã đọc EVE.csv (439/1620)
Đã đọc EVF.csv (440/1620)
Đã đọc EVG.csv (441/1620)
Đã đọc EVS.csv (442/1620)
Đã đọc FBA.csv (443/1620)
Đã đọc FBC.csv (444/1620)
Đã đọc FCC.csv (445/1620)
Đã đọc FCM.csv (446/1620)
Đã đọc FCN.csv (447/1620)
Đã đọc FCS.csv (448/1620)
Đã đọc FDC.csv (449/1620)
Đã đọc FGL.csv (450/1620)
Đã đọc FHN.csv (451/1620)
Đã đọc FHS.csv (452/1620)
Đã đọc FIC.csv (453/1620)
Đã đọc FID.csv (454/1620)
Đã đọc FIR.csv (455/1620)
Đã đọc FIT.csv (456/1620)
Đã đọc FLC.csv (457/1620)
Đã đọc FMC.csv (458/1620)
Đã đọc FOC.csv (459/1620)
Đã đọc FOX.csv (460/1620)
Đã đọc FPT.csv (461/1620)
Đã đọc FRC.csv (462/1620)
Đã đọc FRM.csv (463/1620)
Đã đọc FRT.csv (464/1620)
Đã đọc FSO.csv (465/1620)
Đã đọc FT1.csv (466/1620)
Đã đọc FTI.csv (467/1620)
Đã đọc FTM.csv (468/1620)
Đã đọc FTS.csv (469/1620)
Đã đọc G20.csv (470/1620)
Đã đọc G36.csv (471/1620)
Đã đọc GAB.csv (472/1620)
Đã đọc GAS.csv (473/1620)
Đã đọc GCB.csv (474/1620)
Đã đọc GCF.csv (475/1620)
Đã đọc GDA.csv (476/1620)
Đã đọc GDT.csv (477/1620)
Đã đọc GDW.csv (478/1620)
Đã đọc GEE.csv (479/1620)
Đã đọc GEG.csv (480/1620)
Đã đọc GER.csv (481/1620)
Đã đọc GEX.csv (482/1620)
Đã đọc GGG.csv (483/1620)
Đã đọc GH3.csv (484/1620)
Đã đọc GHC.csv (485/1620)
Đã đọc GIC.csv (486/1620)
Đã đọc GIL.csv (487/1620)
Đã đọc GKM.csv (488/1620)
Đã đọc GLC.csv (489/1620)
Đã đọc GLT.csv (490/1620)
Đã đọc GLW.csv (491/1620)
Đã đọc GMA.csv (492/1620)
Đã đọc GMC.csv (493/1620)
Đã đọc GMD.csv (494/1620)
Đã đọc GMH.csv (495/1620)
Đã đọc GMX.csv (496/1620)
Đã đọc GND.csv (497/1620)
Đã đọc GPC.csv (498/1620)
Đã đọc GSM.csv (499/1620)
Đã đọc GSP.csv (500/1620)
Đã đọc GTA.csv (501/1620)
Đã đọc GTD.csv (502/1620)
Đã đọc GTS.csv (503/1620)
Đã đọc GTT.csv (504/1620)
Đã đọc GVR.csv (505/1620)
Đã đọc GVT.csv (506/1620)
Đã đọc H11.csv (507/1620)
Đã đọc HAC.csv (508/1620)
Đã đọc HAD.csv (509/1620)
Đã đọc HAF.csv (510/1620)
Đã đọc HAG.csv (511/1620)
Đã đọc HAH.csv (512/1620)
Đã đọc HAI.csv (513/1620)
Đã đọc HAM.csv (514/1620)
Đã đọc HAN.csv (515/1620)
Đã đọc HAP.csv (516/1620)
Đã đọc HAR.csv (517/1620)
Đã đọc HAS.csv (518/1620)
Đã đọc HAT.csv (519/1620)
Đã đọc HAV.csv (520/1620)
Đã đọc HAX.csv (521/1620)
Đã đọc HBC.csv (522/1620)
Đã đọc HBD.csv (523/1620)
Đã đọc HBH.csv (524/1620)
Đã đọc HBS.csv (525/1620)
Đã đọc HC1.csv (526/1620)
Đã đọc HC3.csv (527/1620)
Đã đọc HCB.csv (528/1620)
Đã đọc HCC.csv (529/1620)
Đã đọc HCD.csv (530/1620)
Đã đọc HCI.csv (531/1620)
Đã đọc HCM.csv (532/1620)
Đã đọc HCT.csv (533/1620)
Đã đọc HD2.csv (534/1620)
Đã đọc HD6.csv (535/1620)
Đã đọc HD8.csv (536/1620)
Đã đọc HDA.csv (537/1620)
Đã đọc HDB.csv (538/1620)
Đã đọc HDC.csv (539/1620)
Đã đọc HDG.csv (540/1620)
Đã đọc HDM.csv (541/1620)
Đã đọc HDO.csv (542/1620)
Đã đọc HDP.csv (543/1620)
Đã đọc HDS.csv (544/1620)
Đã đọc HDW.csv (545/1620)
Đã đọc HEC.csv (546/1620)
Đã đọc HEJ.csv (547/1620)
Đã đọc HEM.csv (548/1620)
Đã đọc HEP.csv (549/1620)
Đã đọc HES.csv (550/1620)
Đã đọc HEV.csv (551/1620)
Đã đọc HFB.csv (552/1620)
Đã đọc HFC.csv (553/1620)
Đã đọc HFX.csv (554/1620)
Đã đọc HGM.csv (555/1620)
Đã đọc HGT.csv (556/1620)
Đã đọc HGW.csv (557/1620)
Đã đọc HHC.csv (558/1620)
Đã đọc HHG.csv (559/1620)
Đã đọc HHN.csv (560/1620)
Đã đọc HHP.csv (561/1620)
Đã đọc HHS.csv (562/1620)
Đã đọc HHV.csv (563/1620)
Đã đọc HID.csv (564/1620)
Đã đọc HIG.csv (565/1620)
Đã đọc HII.csv (566/1620)
Đã đọc HIO.csv (567/1620)
Đã đọc HJC.csv (568/1620)
Đã đọc HJS.csv (569/1620)
Đã đọc HKB.csv (570/1620)
Đã đọc HKT.csv (571/1620)
Đã đọc HLA.csv (572/1620)
Đã đọc HLB.csv (573/1620)
Đã đọc HLC.csv (574/1620)
Đã đọc HLD.csv (575/1620)
Đã đọc HLO.csv (576/1620)
Đã đọc HLR.csv (577/1620)
Đã đọc HLS.csv (578/1620)
Đã đọc HLT.csv (579/1620)
Đã đọc HLY.csv (580/1620)
Đã đọc HMC.csv (581/1620)
Đã đọc HMD.csv (582/1620)
Đã đọc HMG.csv (583/1620)
Đã đọc HMH.csv (584/1620)
Đã đọc HMR.csv (585/1620)
Đã đọc HMS.csv (586/1620)
Đã đọc HNA.csv (587/1620)
Đã đọc HNB.csv (588/1620)
Đã đọc HND.csv (589/1620)
Đã đọc HNF.csv (590/1620)
Đã đọc HNG.csv (591/1620)
Đã đọc HNI.csv (592/1620)
Đã đọc HNM.csv (593/1620)
Đã đọc HNP.csv (594/1620)
Đã đọc HNR.csv (595/1620)
Đã đọc HOM.csv (596/1620)
Đã đọc HOT.csv (597/1620)
Đã đọc HPB.csv (598/1620)
Đã đọc HPD.csv (599/1620)
Đã đọc HPG.csv (600/1620)
Đã đọc HPH.csv (601/1620)
Đã đọc HPI.csv (602/1620)
Đã đọc HPM.csv (603/1620)
Đã đọc HPP.csv (604/1620)
Đã đọc HPT.csv (605/1620)
Đã đọc HPW.csv (606/1620)
Đã đọc HPX.csv (607/1620)
Đã đọc HQC.csv (608/1620)
Đã đọc HRB.csv (609/1620)
Đã đọc HRC.csv (610/1620)
Đã đọc HRT.csv (611/1620)
Đã đọc HSA.csv (612/1620)
Đã đọc HSG.csv (613/1620)
Đã đọc HSI.csv (614/1620)
Đã đọc HSL.csv (615/1620)
Đã đọc HSM.csv (616/1620)
Đã đọc HSP.csv (617/1620)
Đã đọc HSV.csv (618/1620)
Đã đọc HT1.csv (619/1620)
Đã đọc HTC.csv (620/1620)
Đã đọc HTE.csv (621/1620)
Đã đọc HTG.csv (622/1620)
Đã đọc HTI.csv (623/1620)
Đã đọc HTL.csv (624/1620)
Đã đọc HTM.csv (625/1620)
Đã đọc HTN.csv (626/1620)
Đã đọc HTP.csv (627/1620)
Đã đọc HTT.csv (628/1620)
Đã đọc HTV.csv (629/1620)
Đã đọc HU1.csv (630/1620)
Đã đọc HU3.csv (631/1620)
Đã đọc HU4.csv (632/1620)
Đã đọc HU6.csv (633/1620)
Đã đọc HUB.csv (634/1620)
Đã đọc HUG.csv (635/1620)
Đã đọc HUT.csv (636/1620)
Đã đọc HVA.csv (637/1620)
Đã đọc HVG.csv (638/1620)
Đã đọc HVH.csv (639/1620)
Đã đọc HVN.csv (640/1620)
Đã đọc HVT.csv (641/1620)
Đã đọc HVX.csv (642/1620)
Đã đọc HWS.csv (643/1620)
Đã đọc IBC.csv (644/1620)
Đã đọc IBD.csv (645/1620)
Đã đọc ICC.csv (646/1620)
Đã đọc ICF.csv (647/1620)
Đã đọc ICI.csv (648/1620)
Đã đọc ICN.csv (649/1620)
Đã đọc ICT.csv (650/1620)
Đã đọc IDC.csv (651/1620)
Đã đọc IDI.csv (652/1620)
Đã đọc IDJ.csv (653/1620)
Đã đọc IDP.csv (654/1620)
Đã đọc IDV.csv (655/1620)
Đã đọc IFS.csv (656/1620)
Đã đọc IHK.csv (657/1620)
Đã đọc IJC.csv (658/1620)
Đã đọc ILA.csv (659/1620)
Đã đọc ILB.csv (660/1620)
Đã đọc ILC.csv (661/1620)
Đã đọc ILS.csv (662/1620)
Đã đọc IME.csv (663/1620)
Đã đọc IMP.csv (664/1620)
Đã đọc IN4.csv (665/1620)
Đã đọc INC.csv (666/1620)
Đã đọc ING.csv (667/1620)
Đã đọc INN.csv (668/1620)
Đã đọc IPA.csv (669/1620)
Đã đọc IRC.csv (670/1620)
Đã đọc ISG.csv (671/1620)
Đã đọc ISH.csv (672/1620)
Đã đọc IST.csv (673/1620)
Đã đọc ITA.csv (674/1620)
Đã đọc ITC.csv (675/1620)
Đã đọc ITD.csv (676/1620)
Đã đọc ITQ.csv (677/1620)
Đã đọc ITS.csv (678/1620)
Đã đọc IVS.csv (679/1620)
Đã đọc JOS.csv (680/1620)
Đã đọc JVC.csv (681/1620)
Đã đọc KAC.csv (682/1620)
Đã đọc KBC.csv (683/1620)
Đã đọc KCB.csv (684/1620)
Đã đọc KCE.csv (685/1620)
Đã đọc KDC.csv (686/1620)
Đã đọc KDH.csv (687/1620)
Đã đọc KDM.csv (688/1620)
Đã đọc KGM.csv (689/1620)
Đã đọc KHD.csv (690/1620)
Đã đọc KHG.csv (691/1620)
Đã đọc KHL.csv (692/1620)
Đã đọc KHP.csv (693/1620)
Đã đọc KHS.csv (694/1620)
Đã đọc KHW.csv (695/1620)
Đã đọc KIP.csv (696/1620)
Đã đọc KKC.csv (697/1620)
Đã đọc KLB.csv (698/1620)
Đã đọc KLF.csv (699/1620)
Đã đọc KMR.csv (700/1620)
Đã đọc KMT.csv (701/1620)
Đã đọc KOS.csv (702/1620)
Đã đọc KPF.csv (703/1620)
Đã đọc KSB.csv (704/1620)
Đã đọc KSD.csv (705/1620)
Đã đọc KSF.csv (706/1620)
Đã đọc KSH.csv (707/1620)
Đã đọc KSQ.csv (708/1620)
Đã đọc KST.csv (709/1620)
Đã đọc KSV.csv (710/1620)
Đã đọc KTC.csv (711/1620)
Đã đọc KTL.csv (712/1620)
Đã đọc KTS.csv (713/1620)
Đã đọc KTT.csv (714/1620)
Đã đọc KTW.csv (715/1620)
Đã đọc KVC.csv (716/1620)
Đã đọc KWA.csv (717/1620)
Đã đọc L10.csv (718/1620)
Đã đọc L12.csv (719/1620)
Đã đọc L14.csv (720/1620)
Đã đọc L18.csv (721/1620)
Đã đọc L35.csv (722/1620)
Đã đọc L40.csv (723/1620)
Đã đọc L43.csv (724/1620)
Đã đọc L44.csv (725/1620)
Đã đọc L45.csv (726/1620)
Đã đọc L61.csv (727/1620)
Đã đọc L62.csv (728/1620)
Đã đọc L63.csv (729/1620)
Đã đọc LAF.csv (730/1620)
Đã đọc LAI.csv (731/1620)
Đã đọc LAS.csv (732/1620)
Đã đọc LAW.csv (733/1620)
Đã đọc LBC.csv (734/1620)
Đã đọc LBE.csv (735/1620)
Đã đọc LBM.csv (736/1620)
Đã đọc LCC.csv (737/1620)
Đã đọc LCD.csv (738/1620)
Đã đọc LCG.csv (739/1620)
Đã đọc LCM.csv (740/1620)
Đã đọc LCS.csv (741/1620)
Đã đọc LDG.csv (742/1620)
Đã đọc LDP.csv (743/1620)
Đã đọc LDW.csv (744/1620)
Đã đọc LEC.csv (745/1620)
Đã đọc LG9.csv (746/1620)
Đã đọc LGC.csv (747/1620)
Đã đọc LGL.csv (748/1620)
Đã đọc LGM.csv (749/1620)
Đã đọc LHC.csv (750/1620)
Đã đọc LHG.csv (751/1620)
Đã đọc LIC.csv (752/1620)
Đã đọc LIG.csv (753/1620)
Đã đọc LIX.csv (754/1620)
Đã đọc LKW.csv (755/1620)
Đã đọc LLM.csv (756/1620)
Đã đọc LM3.csv (757/1620)
Đã đọc LM7.csv (758/1620)
Đã đọc LM8.csv (759/1620)
Đã đọc LMC.csv (760/1620)
Đã đọc LMH.csv (761/1620)
Đã đọc LMI.csv (762/1620)
Đã đọc LNC.csv (763/1620)
Đã đọc LO5.csv (764/1620)
Đã đọc LPB.csv (765/1620)
Đã đọc LPT.csv (766/1620)
Đã đọc LQN.csv (767/1620)
Đã đọc LSG.csv (768/1620)
Đã đọc LSS.csv (769/1620)
Đã đọc LTC.csv (770/1620)
Đã đọc LTG.csv (771/1620)
Đã đọc LUT.csv (772/1620)
Đã đọc M10.csv (773/1620)

In [4]:
df = pd.read_csv(r"E:\New folder\stock\all_stocks.csv")
df.head()

         time   open   high    low  close  volume symbol
0  2024-01-02  27.22  27.22  27.22  27.22     415    A32
1  2024-01-03  26.61  26.61  26.08  26.34    1000    A32
2  2024-01-04  26.34  26.34  26.34  26.34     200    A32
3  2024-01-05  26.34  26.34  26.34  26.34       0    A32
4  2024-01-08  26.34  26.34  26.34  26.34       0    A32

In [5]:
df['time'] = pd.to_datetime(df['time'])
df = df.sort_values(by=['symbol', 'time']).reset_index(drop=True)

In [6]:
print("---- EDA quick view ----")
print("Số dòng:", len(df), "| Số mã:", df["symbol"].nunique(),
      "| Khoảng thời gian:", df["time"].min().date(), "->", df["time"].max().date())
print(df[["open","high","low","close","volume"]].describe().round(3))

---- EDA quick view ----
Số dòng: 515294 | Số mã: 1620 | Khoảng thời gian: 2024-01-02 -> 2025-08-01
             open        high         low       close        volume
count  515294.000  515294.000  515294.000  515294.000  5.152940e+05
mean       20.794      21.015      20.568      20.806  6.328032e+05
std        28.606      28.911      28.324      28.636  3.121300e+06
min         0.040       0.040       0.040       0.040  0.000000e+00
25%         7.540       7.610       7.420       7.540  2.800000e+01
50%        13.000      13.090      12.800      13.000  4.100000e+03
75%        24.550      24.870      24.300      24.570  9.900000e+04
max       700.000     710.000     680.000     685.000  2.496817e+08

In [7]:
df.isnull().sum()

time      0
open      0
high      0
low       0
close     0
volume    0
symbol    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515294 entries, 0 to 515293
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   time    515294 non-null  datetime64[ns]
 1   open    515294 non-null  float64
 2   high    515294 non-null  float64
 3   low     515294 non-null  float64
 4   close   515294 non-null  float64
 5   volume  515294 non-null  int64
 6   symbol  515294 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 27.5+ MB

In [9]:
duplicates = df.duplicated().sum()
print("Số dòng trùng lặp:", duplicates)

Số dòng trùng lặp: 0

In [10]:
df.head()

        time   open   high    low  close  volume symbol
0 2024-01-02  27.22  27.22  27.22  27.22     415    A32
1 2024-01-03  26.61  26.61  26.08  26.34    1000    A32
2 2024-01-04  26.34  26.34  26.34  26.34     200    A32
3 2024-01-05  26.34  26.34  26.34  26.34       0    A32
4 2024-01-08  26.34  26.34  26.34  26.34       0    A32

In [11]:

    # MA5 và MA10 (theo close)
    df['ma_5'] = df['close'].rolling(window=5).mean()
    df['ma_10'] = df['close'].rolling(window=10).mean()

    # Volatility = (high - low) / low
    df['volatility'] = (df['high'] - df['low']) / df['low']

    # Momentum: so với giá 4 ngày trước
    df['momentum'] = df.groupby('symbol')['close'].transform(lambda x: x / x.shift(4) - 1)

In [12]:
df['target'] = df.groupby('symbol')['close'].shift(-1)
df = df.dropna()

In [13]:
df.head(10)

,time,open,high,low,close,volume,symbol,ma_5,ma_10,volatility,momentum,target
9,2024-01-15,28.10,28.10,28.10,28.10,0,A32,27.748,27.132,0.000000,0.066819,28.98
10,2024-01-16,28.98,28.98,28.98,28.98,100,A32,28.276,27.308,0.000000,0.100228,29.86
11,2024-01-17,29.86,29.86,29.86,29.86,1006,A32,28.980,27.660,0.000000,0.000000,29.86
12,2024-01-18,29.86,29.86,29.86,29.86,2,A32,28.980,28.012,0.000000,0.062633,30.29
13,2024-01-19,30.29,30.29,30.29,30.29,100,A32,29.418,28.407,0.000000,0.077936,28.10
14,2024-01-22,27.22,28.10,27.22,28.10,200,A32,29.418,28.583,0.032329,-0.030366,27.66
15,2024-01-23,27.66,27.66,27.66,27.66,0,A32,29.154,28.715,0.000000,-0.073677,27.66
16,2024-01-24,27.66,27.66,27.66,27.66,0,A32,28.714,28.847,0.000000,-0.073677,30.73
17,2024-01-25,30.73,30.73,30.73,30.73,100,A32,28.888,28.934,0.000000,0.014526,35.21
18,2024-01-26,33.37,35.21,33.37,35.21,301,A32,29.872,29.645,0.055139,0.253025,39.34

In [14]:
# Encode symbol
le = LabelEncoder()
df['symbol_encoded'] = le.fit_transform(df['symbol'])

# Bỏ NaN (do shift tạo ra)
df = df.dropna()

# Giữ lại date để vẽ sau
dates = df['time']

# Chọn features và target
X = df[['open', 'high', 'low', 'close', 'volume',
        'ma_5', 'ma_10', 'volatility', 'momentum', 'symbol_encoded']]
y = df['target']

In [15]:
# Train-test split
X_train, X_test, y_train, y_test, dates_train, dates_test = train_test_split(
    X, y, dates, test_size=0.2, shuffle=False
)

In [16]:
X_train.dtypes

open              float64
high              float64
low               float64
close             float64
volume              int64
ma_5              float64
ma_10             float64
volatility        float64
momentum          float64
symbol_encoded      int32
dtype: object

In [17]:
# ----- 2. Định nghĩa các model regression -
regressors = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(),
    'XGBoost': XGBRegressor(objective="reg:squarederror", verbosity=0),
    'CatBoost': CatBoostRegressor(verbose=0)
}

In [18]:
# ----- 3. Đánh giá bằng Cross Validation -----
for name, reg in regressors.items():
    reg.fit(X_train, y_train)
    
    # Cross Validation với scoring RMSE, MAE, R^2
    rmse_scores = cross_val_score(reg, X_train, y_train, cv=5, 
                                  scoring='neg_mean_squared_error')
    mae_scores = cross_val_score(reg, X_train, y_train, cv=5, 
                                 scoring='neg_mean_absolute_error')
    r2_scores = cross_val_score(reg, X_train, y_train, cv=5, 
                                scoring='r2')

    print(f"{name:20s} | "
          f"RMSE = {np.sqrt(-rmse_scores.mean()):.4f}, "
          f"MAE = {-mae_scores.mean():.4f}, "
          f"R² = {r2_scores.mean():.4f}")

Linear Regression    | RMSE = 1.0713, MAE = 0.3412, R² = 0.9983
Random Forest        | RMSE = 1.1928, MAE = 0.4295, R² = 0.9979
XGBoost              | RMSE = 1.2141, MAE = 0.3934, R² = 0.9979
CatBoost             | RMSE = 5.5015, MAE = 0.7252, R² = 0.9639

In [20]:
# ========================
# RANDOM FOREST
# ========================
rf_params = {
    "n_estimators": [100, 200],
    "max_depth": [None, 5, 10],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}
grid_rf = GridSearchCV(
    RandomForestRegressor(random_state=42),
    rf_params,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)
grid_rf.fit(X_train, y_train)
rf_reg = grid_rf.best_estimator_

print("Best RF Params:", grid_rf.best_params_)

y_pred_rf = rf_reg.predict(X_test)
# ========================
# XGBOOST
# ========================
xgb_params = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1],
    'max_depth': [3, 5, 7]
}
grid_xgb = GridSearchCV(
    XGBRegressor(objective='reg:squarederror', random_state=42),
    xgb_params,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=-1
)
grid_xgb.fit(X_train, y_train)
xgb_reg = grid_xgb.best_estimator_

print("Best XGB Params:", grid_xgb.best_params_)

y_pred_xgb = xgb_reg.predict(X_test)

Best RF Params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
Random Forest:
  RMSE: 6.5833580720431035
  MAE : 0.6818442906947604
  R²  : 0.9727141972579946
--------------------------------------------------
Best XGB Params: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}
XGBoost:
  RMSE: 6.816753997264197
  MAE : 0.6892643383773908
  R²  : 0.9707452073925055
--------------------------------------------------

In [28]:
# 6. So sánh kết quả
# ========================
results = pd.DataFrame({
    "Model": ["Random Forest", "XGBoost"],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, y_pred_rf)),
        np.sqrt(mean_squared_error(y_test, y_pred_xgb))
    ],
    "MAE": [
        
        mean_absolute_error(y_test, y_pred_rf),
        mean_absolute_error(y_test, y_pred_xgb)
    ],
    "R²": [
        
        r2_score(y_test, y_pred_rf),
        r2_score(y_test, y_pred_xgb)
    ]
})
print(results)

           Model      RMSE       MAE        R²
0  Random Forest  6.583358  0.681844  0.972714
1        XGBoost  6.816754  0.689264  0.970745